import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import NavBar from '../components/NavBar'
import AboutSection from '../components/AboutSection'
import Footer from '../components/Footer'
import ContactSection from "../components/ContactSection";
import ProjectSection from "../components/ProjectSection";
import FadeHeader from "../components/FadeHeader";
import Articles from "../components/Articles";

export default function Home({articles, categories, homepage}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <FadeHeader/>

        <div className="container-fluid px-0">
          <NavBar />
        </div>

        <AboutSection />
        <ProjectSection/>
          <Articles articles={articles} />
        <ContactSection />

      </main>

     <Footer />
    </div>
  )
}

export async function getStaticProps() {
    // Run API calls in parallel
    const [articlesRes, categoriesRes, homepageRes] = await Promise.all([
        fetchAPI("/articles", { populate: ["image", "category"] }),
        fetchAPI("/categories", { populate: "*" }),
        fetchAPI("/homepage", {
            populate: {
                hero: "*",
                seo: { populate: "*" },
            },
        }),
    ]);

    return {
        props: {
            articles: articlesRes.data,
            categories: categoriesRes.data,
            homepage: homepageRes.data,
        },
        revalidate: 1,
    };
}