import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import NavBar from '../components/NavBar'
import AboutSection from '../components/AboutSection'
import Footer from '../components/Footer'
import ContactSection from "../components/ContactSection";
import ProjectSection from "../components/ProjectSection";

import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="header">
          <h1 className={styles.title}>
            Welcome! My name is <span className={"white"}>Jesse Schoonveld</span><br/>
            And I am a <span className="white">front-end </span>developer
          </h1>
          <Link href="#about">
            <a className={"btn btn-primary mt-3"}>View my work</a>
          </Link>
        </div>

        <div className="container-fluid px-0">
          <NavBar />
        </div>

        <AboutSection />
        <ProjectSection/>
        <ContactSection />

      </main>

     <Footer />
    </div>
  )
}
